### ISSUE TITLE
how can I unregister the broadcast receiver.

### ISSUE THREAD

**Issue by ajit123jain** [ajitsing/AndroidOfflineModeNotifications#1]
I am transferring from one activity to another activity and coming back to previous activity.Where I getting this error 

Activity com.example.aditya.realm.MainActivity2 has leaked IntentReceiver io.realm.internal.network.NetworkStateReceiver@2d148d5 that was originally registered here. Are you missing a call to unregisterReceiver()?
              
So how should I unregister the broadcast receiver?

**Comment by ajitsing** [comment]
Hi @ajit-999 

By looking at the exception it seems like you are not unregistering the network receiver when you are navigating to other activity. The ideal way is to unregister the broadcast receiver in the activity/fragment lifecycle method corresponding to where you registered it. For example:

onCreate() - register
onDestroy() - unregister

onResume() - register
onPause() - unregister

onStart() - register
onStop() - unregister

Any one of the above should be used to register or unregister the broadcast receivers. Let me know if this solves your problem.

Thanks
